export const SET_USERNAME = 'SET_USERNAME';
export type SET_USERNAME = typeof SET_USERNAME;

export const GENERATE_RANDOM_NUMBERS = 'GENERATE_RANDOM_NUMBERS';
export type GENERATE_RANDOM_NUMBERS = typeof GENERATE_RANDOM_NUMBERS;

export const SAVE_THE_USER = 'SAVE_THE_USER';
export type SAVE_THE_USER = typeof SAVE_THE_USER;

export const GET_USER_GUESS = 'GET_USER_GUESS';
export type GET_USER_GUESS = typeof GET_USER_GUESS;

export const SET_ALL_GUESSES = 'SET_ALL_GUESSES';
export type SET_ALL_GUESSES = typeof SET_ALL_GUESSES;

export const RESTART_THE_GAME = 'RESTART_THE_GAME';
export type RESTART_THE_GAME = typeof RESTART_THE_GAME;

export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export type ERROR_MESSAGE = typeof ERROR_MESSAGE;

